### PR TITLE
Test alex

### LINKED ISSUE #88: Disclaimer page not showing fully on API 22

### LINKED ISSUE #100: Change equalizer settings after enable/disabling the microphone causes a crash
I believe this might have been fixed in your branch @atyrrell1

### LINKED ISSUE #101: Removing a preset will apply it on the Default
1. Have 2 presets where one is the Default preset. Ensure that they both have different settings.

2. Remove the preset that is not the Default preset.

3. Notice that the Default preset is using the same preset settings as the one that was deleted.

### PR DESCRIPTION
**Pull request by atyrrell1**
I think I got everything for the Espresso tests. Let me know if I missed anything

### CODE REVIEW

File: app/src/main/java/com/ece493/group5/adjustableaudio/services/MicrophoneService.java [hunk 1]
```diff
@@ -29,6 +30,7 @@ public MicrophoneService getService()
     @Override
     public void onCreate()
     {
+        Log.d("Microphone Service", "Oncreate");
```
Comment (rizwan146) [inline app/src/main/java/com/ece493/group5/adjustableaudio/services/MicrophoneService.java]: remove this

**Review by rizwan146 — APPROVED** [review]

**Review by szuk1 — APPROVED** [review]
