### PR TITLE
Equalizer develop alex

### LINKED ISSUE #11: 1.2.2.5.2 Integrate the equalizer controls

### LINKED ISSUE #16: 1.4.1.1 Equalizer User Interface Development

### LINKED ISSUE #35: 1.4.3.1 Implement EqualizerModel class

### LINKED ISSUE #36: 1.4.3.2 Implement logic to apply EqualizerModel to audio output

### LINKED ISSUE #37: 1.4.4.3.3.1 Implement JSON Serializer/Deserializer

### LINKED ISSUE #38: 1.4.4.3.3.2 Implement Settings Loader

### LINKED ISSUE #39: 1.4.4.3.3.3 Implement Settings Saver

### LINKED ISSUE #61: Seek bars not showing at the start up of the settings fragment
For some reason, the seek bars width gets minimized when the setting fragments start. I've traced it either the setting of the spinner's array adapter and listener.

### LINKED ISSUE #67: Permissions not handled correctly
We only check for the read and write external storage. We don't check for the rest of the permissions. This caused an issue on the emulator when only those permissions were enabled, the microphone service crashed and the app failed.

### PR DESCRIPTION
**Pull request by atyrrell1**

### CODE REVIEW

File: app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java [hunk 1]
```diff
@@ -274,30 +434,34 @@ private void enableEqualizerControls()
...
+                    int millibelLevel = seekBar.getProgress() + lowerEqualizerLevel;
+                    equalizerModelListener.getEqualizerModel().setFrequencyBand(Short.valueOf(equalizerBarPosition).intValue(),
+                            millibelLevel);
+                }
             });
         }
 
         globalVolumeSeekbar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
             @Override
             public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
```
Comment (szuk1) [inline app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java]: Curly brace formatting is inconsistent

File: app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java [hunk 2]
```diff
@@ -306,17 +470,20 @@ public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
             public void onStartTrackingTouch(SeekBar seekBar) {}
 
             @Override
-            public void onStopTrackingTouch(SeekBar seekBar) {}
+            public void onStopTrackingTouch(SeekBar seekBar) {
```
Comment (szuk1) [inline app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java]: Curly brace formatting is inconsistent

File: app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java [hunk 3]
```diff
@@ -306,17 +470,20 @@ public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
...
 
             @Override
-            public void onStopTrackingTouch(SeekBar seekBar) {}
+            public void onStopTrackingTouch(SeekBar seekBar) {
+            }
         });
 
         leftVolumeSeekbar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
             @Override
             public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
```
Comment (szuk1) [inline app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java]: curly brace formatting is inconsistent

File: app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java [hunk 4]
```diff
@@ -334,10 +501,12 @@ public void onStopTrackingTouch(SeekBar seekBar) {
             @Override
             public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
```
Comment (szuk1) [inline app/src/main/java/com/ece493/group5/adjustableaudio/ui/settings/SettingsFragment.java]: curly brace formatting is inconsistent

**Review by szuk1 — APPROVED** [review]

File: app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerPreset.java [hunk 5]
```diff
@@ -5,59 +5,64 @@
 public class EqualizerPreset
```
Comment (rizwan146) [inline app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerPreset.java:5]: Not required, but you can make this class extend AudioData which will provide the necessary getters and setters for all the settings. It might look cleaner that way since we remove some repeated code. However this is not required.

File: app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerModel.java [hunk 6]
```diff
@@ -1,64 +1,174 @@
...
 public class EqualizerModel
 {
+    private static final String TAG = EqualizerModel.class.getSimpleName();
+
     List<EqualizerPreset> equalizerPresets;
+    int currentEqualizerSettingPosition;
+    HashMap<Integer, Integer> currentEqualizerBandValues;
+    int currentLeftVolume;
+    int currentRightVolume;
+    String currentEqualizerName;
```
Comment (rizwan146) [inline app/src/main/java/com/ece493/group5/adjustableaudio/models/EqualizerModel.java:19]: perhaps it might be possible to replace the variables:
```java
    HashMap<Integer, Integer> currentEqualizerBandValues;
    int currentLeftVolume;
    int currentRightVolume;
    String currentEqualizerName;
```
with:
```java
EqualizerPreset currentPreset;
```

which is cleaner in my opinion.

**Review by rizwan146 — APPROVED** [review]
